### ISSUE TITLE
Gulp task

### ISSUE THREAD

**Issue by cesaric** [chris-cmsoft/laravel5-angular2-stub#1]
**mix.task('typescript')** in _gulpfile.js_ doesn't appear to point to a task.  I'm assuming it's supposed to be **mix.task('build-typescript')**?

Everything else seems to work great.  Thx!

**Comment by chris-cmsoft** [comment]
Hi @cesaric.

Thanks for the heads up. **Nice find !**
I have fixed it and also removed some repetitive Template and Style copying.

I hope it made your day slightly easier.
